# Generated by Django 5.1.2 on 2024-10-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='carmake',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
