# Generated by Django 5.1.2 on 2024-10-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteMovie',
            new_name='FavoriteCar',
        ),
    ]
